---
version: 2
updates:
  - package-ecosystem: bundler
    vendor: true
    directory: "/"
    groups:
      ruby-dependencies:
        patterns:
          - "*"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: monthly
