name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0

      - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47 # pin@v1.154.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: build
        run: |
          GEM_NAME=$(ls | grep gemspec | cut -d. -f1)
          echo "Attempting to build gem $GEM_NAME..."
          gem build $GEM_NAME
          if [ $? -eq 0 ]; then
            echo "Gem built successfully!"
          else
            echo "Gem build failed!"
            exit 1
          fi
