name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@b256bd96bb4867e7d23e92e087d9bb697270b725 # pin@v1.163.0
        with:
          bundler-cache: true

      - name: lint
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
