name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0

      - uses: ruby/setup-ruby@d37167af451eb51448db3354e1057b75c4b268f7 # pin@v1.155.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
