name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - uses: ruby/setup-ruby@036ef458ddccddb148a2b9fb67e95a22fdbf728b # pin@v1.160.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
