name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0

      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # pin@v1.153.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
