name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - uses: ruby/setup-ruby@a05e47355e80e57b9a67566a813648fa67d92011 # pin@v1.157.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
