name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - uses: ruby/setup-ruby@54a18e26dbbb1eabc604f317ade9a5788dddef81 # pin@v1.159.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
