name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # pin@v1.161.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
