name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@2654679fe7f7c29875c669398a8ec0791b8a64a1 # pin@v1.215.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
