name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # pin@v1.162.0
        with:
          bundler-cache: true

      - name: test
        run: script/test -k
